"""evita favoritos duplicados por usuario

Revision ID: 1465cde7037e
Revises: d7268aa2f296
Create Date: 2026-08-03 17:24:15.933216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1465cde7037e'
down_revision = 'd7268aa2f296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM favoritos WHERE id NOT IN "
        "(SELECT MIN(id) FROM favoritos GROUP BY user_id, producto_id)"
    )
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_favoritos_user_producto', ['user_id', 'producto_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_favoritos_user_producto', type_='unique')

    # ### end Alembic commands ###
