"""agregar detalles comerciales a productos

Revision ID: d7268aa2f296
Revises: 233538540202
Create Date: 2026-08-01 00:45:27.855961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7268aa2f296'
down_revision = '233538540202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_oferta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=160), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('cepa', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('stock')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('cepa')
        batch_op.drop_column('marca')
        batch_op.drop_column('precio_oferta')

    # ### end Alembic commands ###
